server:
  port: 9000
spring:
  application:
    name: gis-web
  servlet:
    multipart:
      maxFileSize: 2000MB
      maxRequestSize: 2000MB
  datasource:
    username: postgres
    #password: root
    password: IyYmh%kq
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/nbiot?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    url: jdbc:postgresql://192.168.67.27:5432/forestry?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

geoserver:
  ip: 192.168.67.27
  #dir: D:\geoserver-2.20.2-bin\data_dir\workspaces
  #dir: /usr/share/geoserver/data_dir/workspaces
  dir: /home/geoserver/data_dir/workspaces/workspaces
  url: http://192.168.67.15:7070/geoserver/
  username: admin
  password: geoserver
  workspace: grid
  boundingBox: latLonBoundingBox

logging:
  level:
    root: info
    sun.rmi: info
